### ISSUE TITLE
Make cmake optional

### ISSUE THREAD

**Issue by Jake-Shadle** [daxpedda/sentry-contrib-native#12]
I'd like to make building with cmake optional, and default to just using cc to compile all of the C/C++ code. This is mainly due to me wanting to cross compile from linux to windows via clang, which exposes bugs both in some of the cmake scripts for sentry/crashpad/etc, as well as in cmake itself (afaict).

For reference for what this could look like, you can see how we got our [physx-rs](https://github.com/EmbarkStudios/physx-rs/tree/main/physx-sys) crate to compile with just cc so that we could just ignore cmake complications altogether.

The work isn't difficult, but I don't know how you would feel about merging such a change so wanted to open this issue before doing any work.

**Comment by Jake-Shadle** [comment]
Ugh, so unfortunately this doesn't even seem to be a [solved for chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=762167), so I'll close this for now and leave the little work I've done in a branch.

**Comment by daxpedda** [comment]
I kinda missed the notification for this issue :/
I would have preferred this to be implemented upstream, but I'm unsure if this would make sense.
Generally speaking I would merge this, yes.

**Comment by Jake-Shadle** [comment]
Yah, for now I just punted on this and am just uploading libs/crashpad_handler to be downloaded and linked later, which works fine for now, but good to know if I get back to this at some point.
