### ISSUE TITLE
Disable using system zlib

### ISSUE THREAD

**Issue by Jake-Shadle** [daxpedda/sentry-contrib-native#14]
When building crashpad, it can optionally use the system zlib, which defaults to true for non-msvc targets, but it would be nice to either disable that entirely and always build from source, or make it an option we could disable via a feature flag, since we would never want to have an additional system dependency when we can compile it from source instead.

**Comment by daxpedda** [comment]
Blocked on https://github.com/getsentry/sentry-native/issues/354.
