### ISSUE TITLE
Support for aarch64-apple-darwin?

### ISSUE THREAD

**Issue by repi** [daxpedda/sentry-contrib-native#20]
With the new ARM-powered Mac's coming out next week it would be very nice with support for building this crate for the new `aarch64-apple-darwin` target, so filing this as a tracking issue towards it but understand it likely would be quite a bit of build system work to do and may need some upstream dependency fixes and support as well.

Since a month ago it is possible to build towards it with nightly with `cargo +nightly build --target aarch64-apple-darwin` but looks like one runs into build errors with `crashpad` with it right now

**Comment by daxpedda** [comment]
Sorry for my long absence!

Apparently this is already being worked on: https://github.com/getsentry/sentry-native/issues/445.
I would also love to some CI: https://github.com/actions/virtual-environments/issues/2187.

**Comment by daxpedda** [comment]
So this has been fixed upstream now and should work. Sadly I can't even test the build in CI because of https://github.com/actions/virtual-environments/issues/2486.

Feel free to re-open if any issues arise.

**Comment by daxpedda** [comment]
Apparently there is an issue with static zlib compilation, see https://github.com/getsentry/sentry-native/issues/486.
I've already made a PR: https://github.com/getsentry/crashpad/pull/34, https://github.com/daxpedda/sentry-contrib-native/pull/29.
