### ISSUE TITLE
Build error on Apple M1 Macs + docker

### ISSUE THREAD

**Issue by storyalex** [daxpedda/sentry-contrib-native#35]
I'm having trouble when building this on M1 macs in docker.

```
error[E0277]: a value of type `Vec<u8>` cannot be built from an iterator over elements of type `i8`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/sentry-contrib-native-0.3.1/src/ffi.rs:43:55
   |
43 |         path.take_while(|ch| *ch != 0).chain(Some(0)).collect()
   |                                                       ^^^^^^^ value of type `Vec<u8>` cannot be built from `std::iter::Iterator<Item=i8>`
   |
   = help: the trait `FromIterator<i8>` is not implemented for `Vec<u8>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `sentry-contrib-native` due to previous error
```

I was able to create a minimal test case that fails the same way on amd64 mac using `docker run --platform linux/aarch64 --rm -it rust:1.57 sh`
And then running:
```
apt update && apt install cmake
mkdir foo
cd foo
cargo init
echo 'sentry-contrib-native = "0.3.1"' >> Cargo.toml
cargo b
```

Changing to `--platform linux/amd64` builds fine on M1 (be warned though, the build is super slow).

**Environment:**

- OS: macOS 12.1 M1 & amd64
- sentry-contrib-native 0.3.1
- Rust 1.57

Let me know if you need more info or help testing/checking stuff!

**Comment by daxpedda** [comment]
Can you try the current master and tell me how that goes? Sadly I can't test it myself right now.

**Comment by storyalex** [comment]
Tested and it works on M1 and amd64! Thank you @daxpedda
